name: hello
variables:
  - build_type: release
source:
  name: hello
  maintainer: mugglewei
deps:
  - name: foo
    maintainer: mugglewei
    tag: v1.0.0
build:
  fat_pkg: true
jobs:
  build:
    steps:
      - run: >
          cmake \
            -S ${HPB_SOURCE_PATH} \
            -B ${HPB_BUILD_DIR} \
            -DCMAKE_PREFIX_PATH=${HPB_DEPS_DIR} \
            -DCMAKE_INSTALL_PREFIX=${HPB_OUTPUT_DIR} \
            -DCMAKE_BUILD_TYPE=${build_type};
          cmake --build ${HPB_BUILD_DIR} --config ${build_type};
          cmake --build ${HPB_BUILD_DIR} --config ${build_type} --target install;
  package:
    needs: [build]
    steps:
      - run: >
          cd ${HPB_TASK_DIR};
          hpb pack --copy-to ${HPB_ROOT_DIR}/_packages/;
