name: mugglecpp
variables:
  - maintainer: mugglewei
  - repo_name: mugglecpp
  - git_tag: v1.0.1
  - git_url: https://github.com/MuggleWei/mugglecpp.git
  - build_type: release
  - pkg_name: mugglec-${git_tag}-${build_type}
source:
  maintainer: ${maintainer}
  repo: ${repo_name}
  tag: ${git_tag}
  repo_kind: git
  repo_url: ${git_url}
  git_depth: 1
deps:
  - maintainer: mugglewei
    name: mugglec
    tag: v1.0.1
jobs:
  build:
    steps:
      - name: build
        run: >
          cd ${HPB_TASK_DIR};
          cmake \
            -S ${HPB_SOURCE_PATH} \
            -B ${HPB_BUILD_DIR} \
            -DCMAKE_BUILD_TYPE=${build_type} \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_INSTALL_PREFIX=${HPB_OUTPUT_DIR} \
            -DCMAKE_PREFIX_PATH=${HPB_DEPS_DIR};
      - name: install
        run: >
          cmake --build build --target install;
  package:
    needs: [build]
    steps:
      - name: package
        run: >
          cd ${HPB_OUTPUT_DIR};
          tar -czvf ${pkg_name}.tar.gz ./*;
