name: mugglecpp
variables:
  - maintainer: mugglewei
  - name: mugglecpp
  - git_tag: v1.0.3
  - git_url: https://github.com/MuggleWei/mugglecpp.git
  - build_type: release
source:
  maintainer: ${maintainer}
  name: ${name}
  tag: ${git_tag}
  repo_kind: git
  repo_url: ${git_url}
  git_depth: 1
deps:
  - maintainer: mugglewei
    name: mugglec
    tag: v1.0.2
jobs:
  build:
    steps:
      - name: build
        run: >
          cd ${HPB_TASK_DIR};
          cmake \
            -S ${HPB_SOURCE_PATH} \
            -B ${HPB_BUILD_DIR} \
            -DCMAKE_BUILD_TYPE=${build_type} \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_INSTALL_PREFIX=${HPB_OUTPUT_DIR} \
            -DCMAKE_PREFIX_PATH=${HPB_DEPS_DIR};
      - name: install
        run: >
          cmake --build ${HPB_BUILD_DIR} --target install;
  package:
    needs: [build]
    steps:
      - name: pack
        run: >
          cd ${HPB_TASK_DIR};
          hpb pack;
  upload:
    needs: [package]
    steps:
      - name: upload
        run: >
          hpb push;
