name: docker build
variables:
  - registry: hpb
  - os: ubuntu
  - os_ver: 22.04
  - img_name: ${registry}/docker_${HPB_TASK_NAME}_${HPB_TASK_ID}:${os}${os_ver}
  - extract_name: extract
jobs:
  build:
    steps:
      - name: docker_build
        run: >
          cd ${HPB_TASK_DIR};
          cp ${yml_filepath} ${HPB_TASK_DIR}/build.yml;
          docker build \
            --network host \
            --build-arg REGISTRY=${registry} \
            --build-arg OS=${os} \
            --build-arg OS_VER=${os_ver} \
            --build-arg FILENAME=build.yml \
            --network host \
            -f ${HPB_FILE_DIR}/Dockerfile \
            -t ${img_name} \
            .;
      - name: extract
        run: >
          docker container create --name ${extract_name} ${img_name};
          docker container cp ${extract_name}:/root/.hpb/artifacts ${HPB_OUTPUT_DIR};
          docker container rm -f ${extract_name};
          docker rmi ${img_name}
