name: mugglec
variables:
  - owner: mugglewei
  - repo_name: mugglec
  - GIT_TAG: v1.0.0
  - git_url: https://github.com/MuggleWei/mugglec.git
  - BUILD_TYPE: release
  - pkg_name: mugglec-${GIT_TAG}-${BUILD_TYPE}
source:
  owner: ${owner}
  repo: ${repo_name}
  tag: ${GIT_TAG}
  repo_kind: git
  repo_url: ${git_url}
  git_depth: 1
test_deps:
  - owner: google
    name: googletest
    tag: v1.13.0
jobs:
  build:
    steps:
      - name: build
        run: >
          cd ${LPB_TASK_DIR};
          mkdir -p build;
          mkdir -p usr;
          cmake \
            -S ${LPB_SOURCE_PATH} \
            -B build \
            -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_INSTALL_PREFIX=${LPB_TASK_DIR}/usr;
  package:
    needs: [build]
    steps:
      - name: package
        run: >
          cmake --build build --target install;
          cd usr;
          tar -czvf ${pkg_name}.tar.gz ./*;
  upload:
    needs: [package]
    steps:
      - name: upload
        run: >
          lpb upload \
            -p ${pkg_name}.tar.gz \
            -c ${LPB_FILE_PATH} \
            --owner ${owner} \
            --repo ${repo_name} \
            --ver ${GIT_TAG} \
            --build-type ${BUILD_TYPE};
          mv ${pkg_name}.tar.gz ${LPB_OUTPUT_DIR};
