name: googletest
variables:
  - owner: google
  - repo_name: googletest
  - git_tag: v1.13.0
  - git_url: https://github.com/google/googletest.git
  - build_type: release
  - pkg_name: googletest-${git_tag}-${build_type}
source:
  owner: ${owner}
  repo: ${repo_name}
  tag: ${git_tag}
  repo_kind: git
  repo_url: ${git_url}
  git_depth: 1
jobs:
  build:
    steps:
      - name: build
        run: >
          cd ${HPB_TASK_DIR};
          cmake \
            -S ${HPB_SOURCE_PATH} \
            -B ${HPB_BUILD_DIR} \
            -DCMAKE_BUILD_TYPE=${build_type} \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_INSTALL_PREFIX=${HPB_PKG_DIR};
          cmake --build ./build --target install;
  package:
    needs: [build]
    steps:
      - name: package
        run: >
          cmake --build build --target install;
          cd ${HPB_PKG_DIR};
          tar -czvf ${pkg_name}.tar.gz ./*;
  upload:
    needs: [package]
    steps:
      - name: upload
        run: >
          hpb upload \
            -p ${pkg_name}.tar.gz \
            -c ${HPB_FILE_PATH} \
            --owner ${owner} \
            --repo ${repo_name} \
            --ver ${git_tag} \
            --build-type ${build_type};
          mv ${pkg_name}.tar.gz ${HPB_OUTPUT_DIR};
