name: googletest
variables:
  - GIT_TAG: v1.13.0
  - BUILD_TYPE: release
  - git_url: https://github.com/google/googletest.git
  - pkg_name: googletest-${GIT_TAG}-${BUILD_TYPE}
jobs:
  prepare:
    steps:
      - name: prepare
        run: >
          cd ${LPB_TASK_DIR};
          git clone --depth=1 --branch=${GIT_TAG} ${git_url};
  build:
    needs: [prepare]
    steps:
      - name: build
        run: >
          cd googletest;
          mkdir -p build;
          mkdir -p usr;
          cmake \
            -S . -B build \
            -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_INSTALL_PREFIX=./usr;
          cmake --build ./build --target install;
  package:
    needs: [build]
    steps:
      - name: package
        run: >
          cd ${LPB_TASK_DIR}/googletest/usr;
          tar -czvf ${pkg_name}.tar.gz ./*;
          mv ${pkg_name}.tar.gz ${LPB_OUTPUT_DIR};
