name: Local Build
jobs:
  build:
    steps:
      - name: prepare
        run: >
          cd ${LPB_OUTPUT_DIR}
          mkdir -p deps;
          mkdir -p build;
          mkdir -p usr;
          git clone \
            --depth=1 \
            --branch=${GIT_TAG} \
            https://github.com/google/googletest.git;
          cmake .. \
            -S ${LPB_OUTPUT_DIR}/googletest \
            -B ${LPB_OUTPUT_DIR}/build \
            -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_INSTALL_PREFIX=${LPB_OUTPUT_DIR}/_usr;
          cmake --build ${LPB_OUTPUT_DIR}/googletest --target install;
          cd ${LPB_OUTPUT_DIR}/usr;
          tar -czvf googletest-${GIT_TAG}-${BUILD_TYPE}.tar.gz ./*
