name: Local Build
jobs:
  build:
    steps:
      - name: prepare
        run: >
          cd ${LPB_TASK_DIR};
          git clone --depth=1 --branch=${GIT_TAG} https://github.com/google/googletest.git;
          cd ${LPB_TASK_DIR}/googletest;
          mkdir -p build;
          mkdir -p usr;
          cmake .. -S . -B build -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=./usr;
          cmake --build ./build --target install;
          cd ${LPB_TASK_DIR}/googletest/usr;
          echo $(PWD);
          tar -czvf googletest-${GIT_TAG}-${BUILD_TYPE}.tar.gz ./*
          mv googletest-${GIT_TAG}-${BUILD_TYPE}.tar.gz ${LPB_OUTPUT_DIR}
