name: Local Build
jobs:
  build:
    steps:
      - name: prepare
        run: >
          cd ${LPB_OUTPUT_DIR};
          mkdir -p deps;
          mkdir -p build;
          mkdir -p usr;
          lpb pull googletest-v1.13.0.tar.gz .
          git clone --depth=1 --branch=${GIT_TAG} https://github.com/MuggleWei/mugglec.git;
      - name: build
        run: >
          mkdir -p build;
          mkdir -p usr;
          cmake .. \
            -S mugglec
            -B build
            -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
            -DBUILD_SHARED_LIBS=ON
            -DCMAKE_INSTALL_PREFIX=${LPB_OUTPUT_DIR}/usr;
      - name: test
        run: echo "test";
      - name: extract
        run: >
          cmake --build ${LPB_ROOT_DIR}/build --target install;
          cd ${LPB_ROOT_DIR}/usr;
          tar -czvf mugglec-${GIT_TAG}-${BUILD_TYPE}.tar.gz ./*;
  extracts:
    needs: build
    steps:
      -name: extracts

