name: Test
jobs:
  job0:
    needs: [job1]
    steps:
      - name: echo
        run: >
          echo "before echo";
          echo "0";
          echo "after echo";
  job1:
    steps:
      - name: echo
        run: >
          echo "before echo";
          echo "1";
          echo "after echo";
  job2:
    needs: [job0, job1]
    steps:
      - name: echo
        run: >
          echo "before echo";
          echo "2";
          echo "after echo";
  job3:
    needs: [job1, job4]
    steps:
      - name: echo
        run: >
          echo "before echo";
          echo "3";
          echo "after echo";
          echo " try ; and ';' and \"aaa\"";
          echo "current dir: $(pwd)";
          echo "LPB_ROOT_DIR: ${LPB_ROOT_DIR}";
          echo "LPB_OUTPUT_DIR: ${LPB_OUTPUT_DIR}";
          cd ${LPB_OUTPUT_DIR};
          echo "current dir: $(pwd)";
          cd ${LPB_TASK_DIR};
          echo "current dir: $(pwd)";
          echo "a-" \
            "b-" \
            "c-";
  job4:
    needs: [job2]
    steps:
      - name: echo
        run: >
          echo "before echo";
          echo "4";
          echo "after echo";
