name: hello
variables:
  - build_type: release
jobs:
  build:
    steps:
      - run: >
          cmake \
            -S ${HPB_SOURCE_PATH} \
            -B ${HPB_BUILD_DIR} \
            -DCMAKE_INSTALL_PREFIX=${HPB_OUTPUT_DIR}
            -DCMAKE_BUILD_TYPE=${build_type};
          cmake --build ${HPB_BUILD_DIR} --config ${build_type};
          cmake --build ${HPB_BUILD_DIR} --config ${build_type} --target install;