name: hello
variables:
  - build_type: release
deps:
  - name: zlib
    maintainer: madler
    tag: v1.2.13
jobs:
  build:
    steps:
      - run: >
          meson setup ${HPB_BUILD_DIR} \
            --build.pkg-config-path ${HPB_DEPS_DIR} \
            --prefix ${HPB_OUTPUT_DIR} \
            --buildtype ${build_type};
          meson compile -C ${HPB_BUILD_DIR};
          meson install -C ${HPB_BUILD_DIR};
