name: googletest
variables:
  - build_type: release
  - googletest_tag: v1.13.0
  - googletest_url: https://github.com/google/googletest.git
source:
  maintainer: google
  name: googletest
  tag: ${googletest_tag}
  repo_kind: git
  repo_url: ${googletest_url}
  git_depth: 1
jobs:
  build:
    steps:
      - name: build
        run: >
          cd ${HPB_TASK_DIR};
          cmake \
            -S ${HPB_SOURCE_PATH} \
            -B ${HPB_BUILD_DIR} \
            -DCMAKE_BUILD_TYPE=${build_type} \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_INSTALL_PREFIX=${HPB_OUTPUT_DIR};
          cmake --build ${HPB_BUILD_DIR} --config ${build_type};
      - name: install
        run: >
          cmake --build ${HPB_BUILD_DIR} --target install;
  package:
    needs: [build]
    steps:
      - name: pack
        run: >
          cd ${HPB_TASK_DIR};
          hpb pack;
  upload:
    needs: [package]
    steps:
      - name: upload
        run: >
          hpb push;
