name: mugglec
variables:
  - maintainer: mugglewei
  - name: mugglec
  - git_tag: v1.0.2
  - git_url: https://github.com/MuggleWei/mugglec.git
  - build_type: release
  - test_target:
      default: test
      windows: RUN_TESTS
source:
  name: ${name}
  maintainer: ${maintainer}
  tag: ${git_tag}
  repo_kind: git
  repo_url: ${git_url}
  git_depth: 1
test_deps:
  - maintainer: google
    name: googletest
    tag: v1.13.0
jobs:
  build:
    steps:
      - name: build
        run: >
          cd ${HPB_TASK_DIR};
          cmake \
            -S ${HPB_SOURCE_PATH} \
            -B ${HPB_BUILD_DIR} \
            -DCMAKE_BUILD_TYPE=${build_type} \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_INSTALL_PREFIX=${HPB_OUTPUT_DIR} \
            -DCMAKE_PREFIX_PATH="${HPB_DEPS_DIR};${HPB_TEST_DEPS_DIR}" \
            -DMUGGLE_BUILD_TESTING=ON;
          cmake --build ${HPB_BUILD_DIR} --config ${build_type};
      - name: test
        run: >
          cmake --build ${HPB_BUILD_DIR} --target ${test_target};
      - name: install
        run: >
          cmake --build ${HPB_BUILD_DIR} --target install;
  package:
    needs: [build]
    steps:
      - name: pack
        run: >
          cd ${HPB_TASK_DIR};
          hpb pack;
  upload:
    needs: [package]
    steps:
      - name: upload
        run: >
          hpb push;
