name: mugglec docker build
variables:
  - owner: mugglewei
  - repo_name: mugglec
  - git_tag: v1.0.2
  - git_url: https://github.com/MuggleWei/mugglec.git
  - build_type: release
  - registry: hpb
  - os: ubuntu
  - os_ver: 22.04
  - pkg_name: mugglec-${git_tag}-${build_type}-${os}${os_ver}
source:
  owner: ${owner}
  repo: ${repo_name}
  tag: ${git_tag}
  repo_kind: git
  repo_url: ${git_url}
  git_depth: 1
jobs:
  build:
    steps:
      - name: docker_build
        run: >
          cd ${HPB_TASK_DIR};
          cp -r ${HPB_SOURCE_PATH} ./mugglec;
          docker build \
            --network host \
            --build-arg REGISTRY=${registry} \
            --build-arg OS=${os} \
            --build-arg OS_VER=${os_ver} \
            --build-arg SOURCE_PATH=mugglec \
            --build-arg BUILD_TYPE=${build_type} \
            --build-arg PKG_NAME=${pkg_name} \
            -f ${HPB_FILE_DIR}/mugglec.Dockerfile \
            -t ${registry}/mugglec:${git_tag}-${os}${os_ver} \
            .;
      - name: extract
        run: >
          docker container create --name extract-${pkg_name} ${registry}/mugglec:${git_tag}-${os}${os_ver};
          docker container cp extract-${pkg_name}:/pkg/${pkg_name}.tar.gz ${HPB_OUTPUT_DIR};
          docker container rm -f extract-${pkg_name};
          docker rmi ${registry}/mugglec:${git_tag}-${os}${os_ver};
          cd ${HPB_OUTPUT_DIR};
          tar -xzvf ${pkg_name}.tar.gz;
          rm -rf ${pkg_name}.tar.gz;
