name: hello
variables:
  - build_type: release
source:
  name: hello
  maintainer: mugglewei
deps:
  - name: foo
    maintainer: mugglewei
    tag: v1.0.0
build:
  fat_pkg: true
jobs:
  build:
    steps:
      - run: >
          meson setup ${HPB_BUILD_DIR} \
            --pkg-config-path ${HPB_DEPS_DIR}/lib/pkgconfig \
            --prefix ${HPB_OUTPUT_DIR} \
            --buildtype ${build_type};
          meson compile -C ${HPB_BUILD_DIR};
          meson install -C ${HPB_BUILD_DIR};
  package:
    needs: [build]
    steps:
      - run: >
          cd ${HPB_TASK_DIR};
          hpb pack --copy-to ${HPB_ROOT_DIR}/_packages/;
