name: brotli
variables:
  - build_type: release
  - brotli_tag: v1.0.9
  - brotli_url: https://github.com/google/brotli.git
source:
  maintainer: google
  name: brotli
  tag: ${brotli_tag}
  repo_kind: git
  repo_url: ${brotli_url}
  git_depth: 1
jobs:
  build:
    steps:
      - run: >
          cd ${HPB_TASK_DIR};
          cmake \
            -S ${HPB_SOURCE_PATH} \
            -B ${HPB_BUILD_DIR} \
            -DCMAKE_BUILD_TYPE=${build_type} \
            -DCMAKE_INSTALL_PREFIX=${HPB_OUTPUT_DIR} \
            -DCMAKE_PREFIX_PATH=${HPB_DEPS_DIR};
          cmake --build ${HPB_BUILD_DIR} --config ${build_type};
          cmake --build ${HPB_BUILD_DIR} --target install;
  package:
    needs: [build]
    steps:
      - name: pack
        run: >
          hpb pack;
  upload:
    needs: [package]
    steps:
      - name: upload
        run: >
          hpb push;
