name: hello
variables:
  - build_type: release
  - build_fat_pkg: true
  - mugglecpp_tag: v1.0.5
source:
  maintainer: mugglewei
  name: example_build_info
deps:
  - maintainer: mugglewei
    name: mugglecpp
    tag: ${mugglecpp_tag}
build:
  build_type: ${build_type}
  fat_pkg: ${build_fat_pkg}
jobs:
  build:
    steps:
      - name: build
        run: >
          cmake \
            -S ${HPB_SOURCE_PATH} \
            -B ${HPB_BUILD_DIR} \
            -DCMAKE_BUILD_TYPE=${build_type} \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_INSTALL_PREFIX=${HPB_OUTPUT_DIR} \
            -DCMAKE_PREFIX_PATH=${HPB_DEPS_DIR};
          cmake --build ${HPB_BUILD_DIR} --target install;
  package:
    needs: [build]
    steps:
      - name: pack
        run: >
          cd ${HPB_TASK_DIR};
          hpb pack --copy-to ${HPB_ROOT_DIR}/_artifacts;
